version: '3.9'

services:

  # Servicio de PostgreSQL
  postgres:
    image: postgres:latest
    container_name: 'meli_postgresql_service'
    restart: always
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

  # Servicio de pgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: 'meli_pgadmin_service'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres

  # App desarrollo
  ecommerce_dev:
    container_name: 'ecommerce_dev'
    restart: unless-stopped
    env_file: 
      - .docker.env
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
      args:
        - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
      - "9229:9229"
    volumes:
      - .:/project
      - node_modules:/project/node_modules
    depends_on:
      - postgres


volumes:
  node_modules:
  postgres-data:
